<?php

use Illuminate\Database\Seeder;
use App\Color;

class ColorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Color::insert([
            ['name' => 'Apricot'],
            ['name' => 'Apricot and Cream'],
            ['name' => 'Beige'],
            ['name' => 'Black'],
            ['name' => 'Black Brown Brindle'],
            ['name' => 'Black and Apricot Striped'],
            ['name' => 'Black and Beige'],
            ['name' => 'Black and Chestnut'],
            ['name' => 'Black and Cream'],
            ['name' => 'Black and Dark Brown'],
            ['name' => 'Black and Fawn'],
            ['name' => 'Black and Gold'],
            ['name' => 'Black and Light Brown'],
            ['name' => 'Black and Light Brown Striped'],
            ['name' => 'Black and Orange'],
            ['name' => 'Black and Rust'],
            ['name' => 'Black and Tan'],
            ['name' => 'Black and Tan Striped'],
            ['name' => 'Black and Wheaten'],
            ['name' => 'Black and White Dotted'],
            ['name' => 'Black, Dark Brown, and Tan Striped'],
            ['name' => 'Blue'],
            ['name' => 'Blue and Apricot'],
            ['name' => 'Blue and Apricot Striped'],
            ['name' => 'Blue and Dark Blue'],
            ['name' => 'Blue and Fawn'],
            ['name' => 'Blue and Gold'],
            ['name' => 'Blue, Black, and Yellow'],
            ['name' => 'Brown'],
            ['name' => 'Brown and Tan'],
            ['name' => 'Chestnut'],
            ['name' => 'Cream'],
            ['name' => 'Current Topic'],
            ['name' => 'Dark Blue'],
            ['name' => 'Dark Blue and Gold'],
            ['name' => 'Dark Brown'],
            ['name' => 'Dark Brown and Apricot Striped'],
            ['name' => 'Dark Brown and Gold'],
            ['name' => 'Dark Brown and Gold Striped'],
            ['name' => 'Dark Brown and Light Brown Striped'],
            ['name' => 'Dark Brown and Tan'],
            ['name' => 'Dark Brown and Tan Striped'],
            ['name' => 'Everything About Dogs'],
            ['name' => 'Fawn'],
            ['name' => 'Gold'],
            ['name' => 'Gold and Yellow'],
            ['name' => 'Gray'],
            ['name' => 'Gray and Black'],
            ['name' => 'Gray and Gold'],
            ['name' => 'Light Brown'],
            ['name' => 'Light Brown and Fawn'],
            ['name' => 'Light Brown and Gold'],
            ['name' => 'Light Silver'],
            ['name' => 'Light Silver and Dark Blue'],
            ['name' => 'Lilac'],
            ['name' => 'Lilac and Apricot'],
            ['name' => 'Lilac and Orange'],
            ['name' => 'Orange'],
            ['name' => 'Red'],
            ['name' => 'Rust'],
            ['name' => 'Rust and Gold'],
            ['name' => 'Silver'],
            ['name' => 'Silver and Beige'],
            ['name' => 'Silver and Black'],
            ['name' => 'Silver, Black, and Gold'],
            ['name' => 'Tan'],
            ['name' => 'Tan and Apricot'],
            ['name' => 'Wheaten'],
            ['name' => 'White'],
            ['name' => 'White and Apricot'],
            ['name' => 'White and Beige'],
            ['name' => 'White and Black'],
            ['name' => 'White and Blue'],
            ['name' => 'White and Brown'],
            ['name' => 'White and Chestnut'],
            ['name' => 'White and Dark Blue'],
            ['name' => 'White and Dark Brown'],
            ['name' => 'White and Fawn'],
            ['name' => 'White and Gold'],
            ['name' => 'White and Gray'],
            ['name' => 'White and Light Brown'],
            ['name' => 'White and Light Silver'],
            ['name' => 'White and Lilac'],
            ['name' => 'White and Orange'],
            ['name' => 'White and Orange Dotted'],
            ['name' => 'White and Red'],
            ['name' => 'White and Red Dotted'],
            ['name' => 'White and Rust'],
            ['name' => 'White and Silver'],
            ['name' => 'White and Tan'],
            ['name' => 'White and Yellow'],
            ['name' => 'White, Black, and Apricot'],
            ['name' => 'White, Black, and Beige'],
            ['name' => 'White, Black, and Brown Striped'],
            ['name' => 'White, Black, and Dark Brown'],
            ['name' => 'White, Black, and Dark Brown Striped'],
            ['name' => 'White, Black, and Fawn'],
            ['name' => 'White, Black, and Gold'],
            ['name' => 'White, Black, and Light Brown'],
            ['name' => 'White, Black, and Light Brown Striped'],
            ['name' => 'White, Black, and Orange'],
            ['name' => 'White, Black, and Rust'],
            ['name' => 'White, Black, and Tan'],
            ['name' => 'White, Black, and Tan Striped'],
            ['name' => 'White, Dark Blue, and Apricot'],
            ['name' => 'White, Dark Blue, and Beige'],
            ['name' => 'White, Dark Blue, and Gold Dotted'],
            ['name' => 'White, Dark Blue, and Tan'],
            ['name' => 'White, Dark Brown, and Gold'],
            ['name' => 'White, Dark Brown, and Light Brown Striped'],
            ['name' => 'White, Dark Brown, and Tan Striped'],
            ['name' => 'White, Gray, and Black'],
            ['name' => 'White, Gray, and Gold'],
            ['name' => 'White, Light Brown, and Tan'],
            ['name' => 'White, Light Silver, and Dark Blue'],
            ['name' => 'White, Lilac, and Dark Blue'],
            ['name' => 'White, Silver, and Beige'],
            ['name' => 'White, Silver, and Black'],
            ['name' => 'Yellow']
        ]);
    }
}
