on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
name: Deploy website on push, pull request and manually
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ${{ secrets.ftp_path }}
        exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/bootstrap/**
            **/config/**
            **/storage/**
            artisan
            .editorconfig
            .env.example
            .gitattributes
            server.php
